#!/usr/bin/env bash

# Copyright 2025 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Syncs CRD definitions from config/crd/bases/ to the Helm chart templates.
# This script transforms controller-gen output into Helm-ready CRD templates
# by adding Helm template variables for labels and conversion webhook configuration.
#
# Usage: hack/sync-helm-crds.sh

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

HELM_CRD_DIR="${REPO_ROOT_DIR}/config/charts/knative-operator/templates/crds"
CRD_BASES_DIR="${REPO_ROOT_DIR}/config/crd/bases"

# Create the output directory
mkdir -p "${HELM_CRD_DIR}"

# Ensure a recent mikefarah/yq (>= v4.42 for -c flag).
GOFLAGS=-mod=mod go install github.com/mikefarah/yq/v4@v4.52.5
YQ_BIN_DIR="$(go env GOBIN)"
YQ_BIN_DIR="${YQ_BIN_DIR:-$(go env GOPATH)/bin}"
export PATH="${YQ_BIN_DIR}:$PATH"

echo "Syncing CRDs from ${CRD_BASES_DIR} to ${HELM_CRD_DIR}"

for crd_file in "${CRD_BASES_DIR}"/*.yaml; do
  filename=$(basename "${crd_file}")
  # Remove "operator.knative.dev_" prefix for cleaner filenames
  short_name="${filename#operator.knative.dev_}"
  target="${HELM_CRD_DIR}/${short_name}"

  echo "  Processing ${filename} -> crds/${short_name}"

  # Use yq to add Helm labels and conversion webhook to the CRD.
  # The source CRD from controller-gen is pure YAML, so yq can safely process it.
  # Helm template variables like "{{ .Chart.Version }}" are valid YAML strings.
  # The -c flag preserves compact sequence indentation (e.g., "- name:" stays at the same level).
  if ! yq eval -c '
    .metadata.labels."app.kubernetes.io/version" = "{{ .Chart.Version }}" |
    .metadata.labels."app.kubernetes.io/name" = "knative-operator" |
    .spec.conversion = {
      "strategy": "Webhook",
      "webhook": {
        "conversionReviewVersions": ["v1beta1"],
        "clientConfig": {
          "service": {
            "name": "operator-webhook",
            "namespace": "{{ .Release.Namespace }}",
            "path": "/resource-conversion"
          }
        }
      }
    }
  ' "${crd_file}" > "${target}"; then
    echo "ERROR: yq failed to process ${filename}"
    rm -f "${target}"
    exit 1
  fi

  # Prepend auto-generation header
  tmp="${target}.tmp"
  echo "# Code generated by hack/sync-helm-crds.sh; DO NOT EDIT." > "${tmp}"
  cat "${target}" >> "${tmp}"
  mv "${tmp}" "${target}"
done

echo "Done. CRDs synced to ${HELM_CRD_DIR}"
